# NOTE: this was all generated by Gemini, according to the Lab 2 spec.
def to_fp8_lab_spec(twos_comp_str):
    # 1. Convert 2's complement to sign-magnitude [cite: 99]
    val = int(twos_comp_str, 2)
    if twos_comp_str[0] == '1':
        s = "1"
        # Negate: invert bits and add 1 [cite: 101]
        magnitude = ( (~val) + 1 ) & 0xFFF
    else:
        s = "0"
        magnitude = val

    # 2. Count leading zeros to determine exponent [cite: 105]
    # We count zeros starting from the MSB (bit 11) [cite: 17]
    mag_str = format(magnitude, '012b')
    leading_zeros = 0
    for bit in mag_str:
        if bit == '0':
            leading_zeros += 1
        else:
            break

    # Exponent Table from
    if leading_zeros == 1:    e_val = 7
    elif leading_zeros == 2:  e_val = 6
    elif leading_zeros == 3:  e_val = 5
    elif leading_zeros == 4:  e_val = 4
    elif leading_zeros == 5:  e_val = 3
    elif leading_zeros == 6:  e_val = 2
    elif leading_zeros == 7:  e_val = 1
    else:                     e_val = 0 # 8 or more leading zeros

    # 3. Extract Significand and Fifth Bit [cite: 62, 90]
    # The significand starts after the last leading zero.
    # If e_val is 0, significand is the 4 LSBs.
    if e_val == 0:
        f_val = magnitude & 0xF
        fifth_bit = 0 # No fifth bit for e=0 according to logic
    else:
        # Position of the "last leading zero" is (12 - leading_zeros - 1)
        shift_amt = 12 - leading_zeros - 5
        if shift_amt >= 0:
            f_val = (magnitude >> shift_amt + 1) & 0xF
            fifth_bit = (magnitude >> shift_amt) & 1
        else:
            # Shift left if the number is too small to have a 5th bit
            f_val = (magnitude << abs(shift_amt + 1)) & 0xF
            fifth_bit = 0

    # 4. Rounding
    if fifth_bit == 1:
        f_val += 1

        # Handle Significand Overflow
        if f_val > 15: # 10000 in binary
            f_val = f_val >> 1 # Become 1000
            e_val += 1

    # 5. Cap Exponent
    if e_val > 7:
        e_val = 7
        f_val = 15

    return f"{s} {format(e_val, '03b')} {format(f_val, '04b')}"

# Generate the file
with open("lab_results.txt", "w") as f:
    for i in range(4096):
        tc = format(i, '012b')
        fp = to_fp8_lab_spec(tc).replace(" ", "")
        f.write(f"Input (2's Comp): {tc} | Output (FP): {fp}\n")

print("File 'lab_results.txt' generated according to Lab 2 specifications.")